themeshop/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Translate with middleware
Route::group(['middleware' => 'localization'], function(){

    Route::get('/', 'Frontend\HomeController@index')->name('welcome');
    Route::get('/search', 'Frontend\HomeController@search')->name('frontend.search');
    Route::get('/search/json', 'Frontend\HomeController@jsonSearch');
    Route::get('change-language', 'Frontend\HomeController@changeLanguage')->name('change-language');

    Route::get('/redirect/{providerName}', 'Frontend\SocialAuthController@redirect')->name('auth.social');
    Route::get('/callback/{providerName}', 'Frontend\SocialAuthController@callback');

    Auth::routes();

    Route::group(['prefix' => 'admin', 'middleware' => 'isAdmin'], function () {
        Route::get('/', 'Admin\AdminController@index');
        Route::match(['get', 'post'], 'setup', 'Admin\AdminController@setup')->name('admin.setup');
        Route::get('json/getStaticstics', 'Admin\AdminController@getStaticstics');

        Route::resource('users', 'Admin\UserController');

        Route::resource('category', 'Admin\CategoryController');
        Route::get('category/{id}/create', 'Admin\CategoryController@subCreate')->name('category.subCreate');

        Route::resource('product', 'Admin\ProductController');

        Route::resource('comment', 'Admin\CommentController');

        Route::resource('rate', 'Admin\RateController');

        Route::resource('request', 'Admin\RequestProductController');

        Route::get('orders', 'Admin\OrderController@index')->name('admin.orders.index');
        Route::get('orders/{id}/detail', 'Admin\OrderController@orderDetail')->name('admin.orders.detail');
        Route::put('orders/{id}/detail', 'Admin\OrderController@changeStatus')->name('admin.orders.change');
    });

    Route::group(['middleware' => 'isLogin'], function(){
        // Make An Appointment
        Route::get('/preorder', 'Frontend\PreOrderController@index')
            ->name('frontend.preorder.index');
        Route::get('/preorder/json/getList', 'Frontend\PreOrderController@getJsonList');
        Route::delete('/preorder/{id}', 'Frontend\PreOrderController@destroyAnAppointment');

        Route::get('/preorder/{id}/edit', 'Frontend\PreOrderController@editAnAppointment');
        Route::put('/preorder/{id}/edit', 'Frontend\PreOrderController@updateAnAppointment')
            ->name('frontend.preorder.update');

        Route::get('/preorder/addnew', 'Frontend\PreOrderController@addNewAnAppointment')
            ->name('frontend.preorder.addnew');
        Route::post('/preorder/addnew', 'Frontend\PreOrderController@storeNewAnAppointment')
            ->name('frontend.preorder.store');
        Route::get('/preorder/json/searchProducts', 'Frontend\PreOrderController@jsonSeachProducts');

        // Mark Product
        Route::get('/mark-product', 'Frontend\HomeController@markProductIndex')
            ->name('frontend.mark-product.index');
        Route::delete('/mark-product/{id}', 'Frontend\HomeController@markProductDestroy')
            ->name('frontend.mark-product.destroy');

        Route::get('detail/add-to-box', 'Frontend\DetailProductsController@addToBox')->name('add_to_box');

        // Add comment
        Route::post('/comment/send/data', 'Frontend\DetailProductsController@addEditComment');
        Route::post('/comment/send/data/children', 'Frontend\DetailProductsController@addEditChildrenComment');
        Route::post('/comment/delete/children', 'Frontend\DetailProductsController@deleteChildrenComment');

        Route::post('/user/edit', 'Frontend\UserProfilesController@editUserInformations')
            ->name('frontend.user.edit.personal');
        Route::post('/user/edit/upload', 'Frontend\UserProfilesController@showUploadAvatar')
            ->name('show_upload_avatar');
        Route::post('/user/change-password', 'Frontend\UserProfilesController@userChangePassword')
            ->name('user_change_password');
        Route::get('/user/profile', 'Frontend\UserProfilesController@index')
            ->name('frontend.user.profiles');


        Route::get('/make-an-appointment', 'Frontend\RequestMakeAnAppointmentController@requestIndex')
            ->name('make-an-appointment.index');
        Route::get('/make-an-appointment/add-new', 'Frontend\RequestMakeAnAppointmentController@requestAddnew')
            ->name('make-an-appointment.addnew');
        Route::post('/make-an-appointment/add-new', 'Frontend\RequestMakeAnAppointmentController@requestStore')
            ->name('make-an-appointment.store');
        Route::get('/make-an-appointment/json/detail', 'Frontend\RequestMakeAnAppointmentController@jsonDetail');
        Route::get('/make-an-appointment/json/partnerDetail', 'Frontend\RequestMakeAnAppointmentController@jsonPartnerDetail');

        Route::get('/request-product', 'Frontend\RequestProductController@requestIndex')
            ->name('frontend.request-product.index');
        Route::get('/request-product/add-new', 'Frontend\RequestProductController@requestAddnew')
            ->name('frontend.request-product.addnew');
        Route::post('/request-product/add-new', 'Frontend\RequestProductController@requestStore')
            ->name('frontend.request-product.store');
        Route::get('/request-product/json/detail', 'Frontend\RequestProductController@jsonDetail');

        Route::get('/partner-make-an-appointment', 'Frontend\RequestMakeAnAppointmentController@partnerRequestIndex')
            ->name('partner-request-an-appointment.index');
        Route::get('/partner/{id}/preorder', 'Frontend\PreOrderController@partnerMakeAnAppointment')
            ->name('frontend.partner.preorder');
        Route::post('/partner/{id}/preorder', 'Frontend\PreOrderController@partnerStoreAnAppointment')
            ->name('frontend.partner.preorder.store');

        Route::get('/convert-set-product/{id}/order', 'Frontend\OrderController@convertToOrder')
            ->name('frontend.convert.order');
        Route::get('checkout', 'Frontend\OrderController@checkout')->name('frontend.checkout');
        Route::post('checkout', 'Frontend\OrderController@checkoutStore')->name('frontend.checkout.store');
        Route::get('order-view/{id}/detail', 'Frontend\OrderController@detailOrder')
            ->name('frontend.order.detail');
        Route::put('order-view/{id}/detail', 'Frontend\OrderController@changeStatus')
            ->name('frontend.order.change');
        Route::get('checkout/success', 'Frontend\OrderController@orderSuccess')
            ->name('frontend.order.success');
        Route::get('user/order-list', 'Frontend\OrderController@orderList')
            ->name('frontend.order.list');
        Route::post('/order/resend/email', 'Frontend\OrderController@resendEmail');
    });

    Route::get('/user/{user_id}/{user_name}', 'Frontend\UserProfilesController@profileDiffUser')
        ->name('frontend.user.different.profiles');

    Route::get('/partner/list-all', 'Frontend\HomeController@partnerList')->name('frontend.partner.list');
    Route::get('/partner/json/getList', 'Frontend\HomeController@jsonPartnerList');

    Route::post('/detail/{id}/review', 'Frontend\DetailProductsController@reviewProduct');

    Route::get('/contact/sendemail', 'Frontend\HomeController@indexSendEmail')->name('frontend.contact.index');
    Route::post('/contact/sendemail', 'Frontend\HomeController@sendEmail')->name('frontend.sendemail');

    // Comment
    Route::get('/comment/json/getList', 'Frontend\DetailProductsController@jsonCommentList');

    // Detail product
    Route::get('detail/{id}/{name}', 'Frontend\DetailProductsController@index')->name('detail');

    Route::get('/{parent}', 'Frontend\ProductsListController@showParentCategories')->name('nav');
    Route::get('/{parentLink}/{subLink}', 'Frontend\ProductsListController@showSubCategory')->name('sub_Nav');
});

themeshop/resources/views/admin/layouts/library/content-header.blade.php
<header class="main-header">

    <!-- Logo -->
    <a href="{{ url('admin') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>DB</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>{{ __('Admin') }}</b>{!! __('Dashboard') !!}</span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">{{ __('Toggle Navigation') }}</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{!! url('') !!}" target="_blank">{{ __('Go Home Page') }}</a>
                </li>

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        @if (Auth::user()->avatar)
                            <img src="{!! asset(Auth::user()->avatar) !!}" class="user-image">
                        @else
                            <img src="{!! asset('bower_components/AdminLTE/dist/img/avatar.png') !!}" class="user-image">
                        @endif
                        <span class="hidden-xs">{!! Auth::user()->display_name !!}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            @if (Auth::user()->avatar)
                                <img src="{!! asset(Auth::user()->avatar) !!}" class="user-image">
                            @else
                                <img src="{!! asset('bower_components/AdminLTE/dist/img/avatar.png') !!}" class="user-image">
                            @endif
                            <p>
                                <span class="hidden-xs">{!! Auth::user()->display_name !!}</span>
                                <small></small>
                            </p>
                            <p>
                                <small>
                                    {!! Auth::user()->address !!}
                                        - 
                                    {!! Auth::user()->phone !!}
                                </small>
                            </p>
                        </li>

                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-right">
                                {!! Form::open(['url' => url('logout'), 'method' => 'post']) !!}
                                    <a data-toggle="tooltip" class="btn btn-danger" onclick="confirmButtonBeforeSubmit(this)" data-text="{{ __('Do you want to delete?') }}" data-original-title="{{ __('Logout') }}">
                                        {{ __('Logout') }}
                                    </a>
                                {!! Form::close() !!}
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
            </ul>
        </div>
    </nav>
</header>

themeshop/resources/views/admin/layouts/library/footer-js.blade.php
<!-- jQuery -->
<script src="{!! url('bower_components/jquery/dist/jquery.min.js') !!}"></script>
<!-- Knockout JS -->
<script src="{!! url('bower_components/knockout/dist/knockout.js') !!}"></script>
<!-- Bootstrap -->
<script src="{!! url('bower_components/bootstrap/dist/js/bootstrap.min.js') !!}"></script>
<!-- AdminLTE App -->
<script src="{!! url('bower_components/AdminLTE/dist/js/app.min.js') !!}"></script>
<!-- DataTables -->
<script src="{!! url('bower_components/AdminLTE/plugins/datatables/jquery.dataTables.min.js') !!}"></script>
<script src="{!! url('bower_components/AdminLTE/plugins/datatables/dataTables.bootstrap.min.js') !!}"></script>
<!-- FastClick -->
<script src="{!! url('bower_components/AdminLTE/plugins/fastclick/fastclick.min.js') !!}"></script>
<!-- SlimScroll 1.3.0 -->
<script src="{!! url('bower_components/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js') !!}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<script src="{!! url('bower_components/tinymce/tinymce.min.js') !!}"></script>
<script src="{!! url('bower_components/bootstrap-sweetalert/dist/sweetalert.min.js') !!}"></script>
<script src="{!! url('js/admin/custom-config.js') !!}"></script>

themeshop/resources/views/admin/layouts/library/header-css.blade.php
<!-- Bootstrap 3.3.5 -->
<link rel="stylesheet" href="{!! url('bower_components/bootstrap/dist/css/bootstrap.min.css') !!}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{!! url('bower_components/font-awesome/css/font-awesome.min.css') !!}">
<link rel="stylesheet" type="text/css" href="{{ url('css/admin/custom.css') }}" />
<!-- Theme style -->
<link rel="stylesheet" href="{!! url('bower_components/AdminLTE/dist/css/AdminLTE.min.css') !!}">
<link rel="stylesheet" href="{!! url('bower_components/AdminLTE/dist/css/skins/_all-skins.min.css') !!}">
<link rel="stylesheet" href="{!! url('bower_components/AdminLTE/plugins/datatables/dataTables.bootstrap.css') !!}"/>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="{!! url('bower_components/bootstrap-sweetalert/dist/sweetalert.css') !!}"/>

themeshop/resources/views/admin/layouts/library/session-message.blade.php
<!-- type : danger -->
<!-- type : success -->
<?php $messages = Session::get('flash_messages', []) ?>

@foreach ($messages as $message)
	<div class="alert alert-{{ $message['type'] }} alert-dismissible">
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	    <h4>{{ $message['title'] }}</h4>
	    <p>{{ $message['message'] }}</p>
	</div>
@endforeach

themeshop/resources/views/admin/layouts/library/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                @if (Auth::user()->avatar)
                    <img src="{!! asset(Auth::user()->avatar) !!}" class="user-image">
                @else
                    <img src="{!! asset('bower_components/AdminLTE/dist/img/avatar.png') !!}" class="user-image">
                @endif
            </div>
            <div class="pull-left info">
                <p>{!! Auth::user()->display_name !!}</p>
                <a href="#"><i class="fa fa-circle text-success"></i>{{ __('Online') }}</a>
            </div>
        </div>
    
        <ul class="sidebar-menu">
            <li class="header" style=" text-transform: uppercase">
                {{ __('Main Navigation') }}
            </li>
            <li class="treeview">
                <a href="{{ route('users.index') }}">
                    <i class="fa fa-users"></i>
                    <span> {{ __('List Users') }} </span>
                </a>
            </li>
            <li class="treeview">
                <a href="{{ route('category.index') }}">
                    <i class="fa fa-list-ul"></i>
                    <span> {{ __('Category') }} </span>
                </a>
            </li>
            <li class="treeview">
                <a href="{{ route('product.index') }}">
                    <i class="fa fa-medkit"></i>
                    <span> {{ __('Medicine') }} </span>
                </a>
            </li>
            <li class="treeview">
                <a href="{{ route('comment.index') }}">
                    <i class="fa fa-facebook-f"></i>
                    <span> {{ __('Comment') }} </span>
                </a>
            </li>
            <li class="treeview">
                <a href="{{ route('rate.index') }}">
                    <i class="fa fa-star"></i>
                    <span> {{ __('Review Medicine') }} </span>
                </a>
            </li>
            <li class="treeview">
                <a href="{{ route('request.index') }}">
                    <i class="fa  fa-question"></i>
                    <span> {{ __('Request Medicine') }} </span>
                </a>
            </li>
            <li class="treeview">
                <a href="{{ route('admin.orders.index') }}">
                    <i class="fa fa-shopping-cart"></i>
                    <span> {{ __('Orders') }} </span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-windows"></i>
                    <span>{{ __('Website') }}</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{ route('admin.setup') }}">
                            <i class="fa fa-cog"></i>
                            <span>{{ __('Setup Website') }}</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>